//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHATROOM
    {
        public int CHATROOM_ID { get; set; }
        public int ROOM_ID { get; set; }
        public int USER_ID { get; set; }
        public int ISREAD { get; set; }
    
        public virtual ROOM ROOM { get; set; }
        public virtual USER USER { get; set; }
    }
}
