//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.PROGRESSEMPLOYEES = new HashSet<PROGRESSEMPLOYEE>();
            this.TASKEMPLOYEES = new HashSet<TASKEMPLOYEE>();
        }
    
        public int EMPLOYEE_ID { get; set; }
        public string EMPLOYEE_FIRSTNAME { get; set; }
        public string EMPLOYEE_LASTNAME { get; set; }
        public string EMPLOYEE_EMAIL { get; set; }
        public string EMPLOYEE_DESIGNATION { get; set; }
        public string EMPLOYEE_ORGANIZATION { get; set; }
        public string EMPLOYEE_PHONE { get; set; }
        public string EMPLOYEE_GENDER { get; set; }
        public System.DateTime EMPLOYEE_DATEOFBIRTH { get; set; }
        public string EMPLOYEE_LOCATION { get; set; }
        public System.DateTime EMPLOYEE_REGISTRATIONDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROGRESSEMPLOYEE> PROGRESSEMPLOYEES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASKEMPLOYEE> TASKEMPLOYEES { get; set; }
    }
}
