//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANAGER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MANAGER()
        {
            this.TASKMANAGERS = new HashSet<TASKMANAGER>();
        }
    
        public int MANAGER_ID { get; set; }
        public string MANAGER_FIRSTNAME { get; set; }
        public string MANAGER_LASTNAME { get; set; }
        public string MANAGER_EMAIL { get; set; }
        public string MANAGER_DESIGNATION { get; set; }
        public string MANAGER_ORGANIZATION { get; set; }
        public string MANAGER_PHONE { get; set; }
        public string MANAGER_GENDER { get; set; }
        public System.DateTime MANAGER_DATEOFBIRTH { get; set; }
        public string MANAGER_LOCATION { get; set; }
        public System.DateTime MANAGER_REGISTRATIONDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASKMANAGER> TASKMANAGERS { get; set; }
    }
}
