//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRESS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROGRESS()
        {
            this.PROGRESSEMPLOYEES = new HashSet<PROGRESSEMPLOYEE>();
            this.PROGRESSFILES = new HashSet<PROGRESSFILE>();
            this.TASKPROGRESSES = new HashSet<TASKPROGRESS>();
        }
    
        public int PROGRESS_ID { get; set; }
        public string PROGRESS_DESCRIPTION { get; set; }
        public float PROGRESS_PERCENTAGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROGRESSEMPLOYEE> PROGRESSEMPLOYEES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROGRESSFILE> PROGRESSFILES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASKPROGRESS> TASKPROGRESSES { get; set; }
    }
}
