//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTUSER
    {
        public int REPORTUSER_ID { get; set; }
        public int REPORT_ID { get; set; }
        public int USER_ID_BY { get; set; }
        public int USER_ID_FOR { get; set; }
    
        public virtual REPORT REPORT { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
