//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASKMANAGER
    {
        public int TASKMANAGER_ID { get; set; }
        public int TASK_ID { get; set; }
        public int MANAGER_ID { get; set; }
    
        public virtual MANAGER MANAGER { get; set; }
        public virtual TASK TASK { get; set; }
    }
}
